# Generated by Django 5.2.7 on 2025-10-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeenStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(max_length=128, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('reward', models.CharField(blank=True, max_length=64, null=True)),
                ('estimated_time', models.CharField(blank=True, max_length=32, null=True)),
                ('country_code', models.CharField(blank=True, max_length=8, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
